Algoritmo "semnome"
// Disciplina  :  [Linguagem e Lógica de Programação] 
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 20/04/2018
Var
num,x,n:inteiro


Inicio
escreval("Tabuada de 0 a 9")
num<-0
x<-0
enquanto (x<10) faca
escreval(num, "x", x, "=", num*x)
x<-x+1
fimenquanto
Fimalgoritmo