algoritmo "exercício questão 1   "
// Função :
// Autor :
// Data : 07/03/2018
// Seção de Declarações
var
 n1, n2, s, difer, p:inteiro
 m:real


inicio
escreval ("informe um número ")
leia (n1)
escreval ("informe outro número ")
leia (n2)
s<- n1+n2
difer<-n1-n2
m <-(n1+n2)/2
p <- n1*n2
escreval ("a soma dos dois números é ", s," subtração ", difer," a média ", m," o produto", p)
escreval






fimalgoritmo
