Algoritmo "semnome"
// Disciplina  :  [Linguagem e Lógica de Programação] 
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 20/04/2018
Var
x:inteiro


Inicio
para x de 1000 ate 1999 faca
x<-x+0
se (x mod 11 = 5) entao
escreva("este Número dvidido por 11 tem o resto 5 ->",  x)
escreval("")
escreval("")
fimse
fimpara


Fimalgoritmo