Algoritmo "semnome"
// Disciplina  :  [Linguagem e Lógica de Programação] 
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 21/04/2018
Var
x, y :Inteiro



Inicio
x<- 1
y<- 1
Enquanto (x <= 99) e (y <= 50) faca
Escreval ("Sequência:",x,"/",y)
x<- x+2
y<- y+1
fimenquanto
Fimalgoritmo
Fimalgoritmo

